### ISSUE TITLE
Small typo in docker run command

### ISSUE THREAD

**Issue by except-pass** [f-squirrel/dockerized_cpp_build_example#1]
[Brilliant blog post](https://ddanilov.me/dockerized-cpp-build).  You give your docker run command as
` docker run -it -rm --name=example \ <...>` but the correct flag is `--rm` (two hyphens.).  

Thanks again for putting this together.

**Comment by f-squirrel** [comment]
Thank you @except-pass for the catch!
I have updated the post accordingly.
